config/routes.rb
Rails.application.routes.draw do
  
  root to: 'kakakus#index'
  
  resources :kakakus
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kakaku.rb
class Kakaku < ApplicationRecord
  validates :hinnmei, presence: true, length: { maximum: 255 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kakakus_controller.rb
class KakakusController < ApplicationController
  before_action :set_kakaku, only: [:show, :edit, :update, :destroy]
  def index
    @kakaku = Kakaku.all.page(params[:page])
  end

  def show
    set_kakaku
  end

  def new
    @kakaku = Kakaku.new
  end
  
  def create
    @kakaku = Kakaku.new(kakaku_params)
    
    if @kakaku.save
      flash[:success] = '価格表が正常に投稿されました'
      redirect_to @kakaku
    else
      flash.now[:danger] = '価格表が投稿されませんでした'
      render :new
    end
  end

  def edit
    set_kakaku
  end
  
  def update
    set_kakaku
    if @kakaku.update(kakaku_params)
      flash[:success] = '価格表は正常に更新されました'
      redirect_to @kakaku
    else
      flash.now[:danger] = '価格は更新されませんでした'
      render :edit
    end
  end
  
  def destroy
    set_kakaku
    @kakaku.destroy
    
    flash[:success] = '価格は正常に削除されました'
    redirect_to kakakus_url
  end
  
  private
  
  def set_kakaku
    @kakaku = Kakaku.find(params[:id])
  end
  
  #strong parameter
  def kakaku_params
    params.require(:kakaku).permit(:hinnmei,:sikirikakaku,:teika,:bikou,:size)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kakakus_helper.rb
module KakakusHelper
end

app/views/kakakus/_form.html.erb
<div class="row">
  <div class="col-6">
    <%= form_with(model: kakaku, local: true) do |f| %>
    <% if kakaku.errors.any? %>
      <div id="error_explanation" class="alert alert-warning">
        <ul class="mb-0">
          <% kakaku.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
  
  <div class="form-group">
  <%= f.label :hinnmei, '品名' %>
  <%= f.text_field :hinnmei, class: 'form-control' %>
  </div>

  <div class="form-group">
  <%= f.label :sikirikakaku, '仕切価格' %>
  <%= f.text_field :sikirikakaku, class: 'form-control' %>
  </div>
  
  <div class="form-group">
  <%= f.label :teika, '定価' %>
  <%= f.text_field :teika,class: 'form-control' %>
  </div>
  
  <div class="form-group">
  <%= f.label :bikou, '備考' %>
  <%= f.text_field :bikou, class: 'form-control' %>
  </div>
 

      <%= f.submit '投稿', class: 'bnt btn-primary' %>
    <% end %>
  </div>
</div>

app/views/kakakus/edit.html.erb
<h1>id: <%= @kakaku.id %> の価格リスト編集ページ</h1>

<%= render 'form', kakaku: @kakaku %>


<%= link_to '一覧に戻る', kakakus_path %>

app/views/kakakus/index.html.erb
<h1>価格一覧</h1>

<% if @kakaku.any? %>


 <table class="table table-striped">
    <thead>
      <tr>
        <th>品名</th>
        <th>サイズ</th>
        <th>仕切り価格</th>
        <th>定価</th>
        <th>備考</th>
      </tr>
    </thead>
    <tbody>
      <% @kakaku.each do |kakaku| %>
        <tr>
          <td><%= link_to kakaku.hinnmei, kakaku %></td>
          <td><%= kakaku.hinnmei %></td>
          <td><%= kakaku.size %></td>
          <td><%= kakaku.sikirikakaku %></td>
          <td><%= kakaku.teika %></td>
          <td><%= kakaku.bikou %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <%= paginate @kakaku %>
  </div>
<% end %>
  

 
 <%= link_to '新規価格の投稿', new_kakaku_path, class: "btn btn-primary" %>

app/views/kakakus/new.html.erb
<h1>価格の新規登録</h1>

<%= render 'form', kakaku: @kakaku %>

<%= link_to '一覧に戻る', kakakus_path %>

app/views/kakakus/show.html.erb
<h1><%= @kakaku.hinnmei %>の価格表詳細ページ</h1>


<table class="table table-bordered">
  <thead>
    <th scope="col">品名/サイズ</th>
      <th scope="col">仕切り価格</th>
      <th scope="col">定価</th>
      <th scope="col">備考</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @kakaku.hinnmei %></td>
      <td><%= @kakaku.sikirikakaku %></td>
      <td><%= @kakaku.teika %></td>
      <td><%= @kakaku.bikou %></td>
    </tr>
  </tbody>
</table>
  
  

<%= link_to 'この価格リストを編集する', edit_kakaku_path(@kakaku), class: 'btn btn-light' %>
<%= link_to 'この価格リストを削除する', @kakaku, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">KAKAKULIST</a>
    <!-- 横幅が狭い時に出るハンバーガーボタン -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- メニュー項目 -->
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to  '新規価格表の投稿', new_kakaku_path, class: 'nav-link' %></li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Kakakulist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
    <%= yield %>
    </div>
  </body>
</html>